---
- hosts: all
  become: true
  vars:
    srcdir: /tmp/mydumper
  tasks:
  - name: add percona repo
    dnf:
      name: https://repo.percona.com/yum/percona-release-latest.noarch.rpm
      state: present

  - name: disable dnf mysql module
    command: dnf module disable mysql -y
    args:
      warn: false

  - name: ensure pre-requsites are installed
    dnf:
      name:
        - glib2-devel
        - zlib-devel
        - pcre-devel
        - openssl-devel
        - cmake
        - gcc-c++
        - git
      state: present

  - name: install mysql devel
    dnf:
      name: Percona-Server-devel-57
      state: present

  - name: mydumper git repo
    become_user: vagrant
    git:
      accept_hostkey: yes
      repo: https://github.com/maxbube/mydumper.git
      dest: "{{ srcdir }}/"
      update: yes

  - name: clean previous run
    file:
       path: "{{ item }}"
       state: absent
    with_items:
        - "{{ srcdir }}/mydumper"
        - "{{ srcdir }}/myloader"
        - "{{ srcdir }}/CMakeCache.txt"

  - name: cmake mydumper
    command: cmake . -DMYSQL_LIBRARIES_mysqlclient:FILEPATH=/usr/lib64/mysql/libmysqlclient.a
    args:
      chdir: "{{ srcdir }}"

  - name: make mydumper
    make: "chdir={{ srcdir }}"

  - name: fetch binaries
    fetch:
      src: "{{ item }}"
      dest: "/opt/src/mydumper/{{ inventory_hostname }}/"
      flat: yes
    with_items:
      - "{{ srcdir }}/mydumper"
      - "{{ srcdir }}/myloader"

