---
- hosts: all
  become: true
  tasks:
  - name: add percona repo
    yum:
      name: https://www.percona.com/downloads/percona-release/redhat/LATEST/
      state: present

  - name: ensure pre-requsites are installed
    yum:
      name:
        - glib2-devel
        - zlib-devel
        - pcre-devel
        - openssl-devel
        - cmake
        - gcc-c++
        - git
      state: present

  - name: remove installed mysql libs
    yum:
      name: mariadb-libs
      state: absent

  - name: install mysql devel
    yum:
      name: 
      - Percona-Server-devel-57
      - Percona-Server-server-57
      state: present

  - name: Start compiling
    include_tasks: compile_mydumper.yml
    vars:
      srcdir: /tmp/mydumper
      provider: mysql
      clientlibpath: /usr/lib64/mysql/libmysqlclient.a 
      mydumperrepo: https://github.com/maxbube/mydumper.git
      cmake_options: "{{ extra_cmake_options | default('') }}" 
      branch: master
