---
- hosts: all
  become: true
  vars:
    srcdir: /tmp/mydumper
  tasks:
  - name: add percona repo
    yum:
      name: https://www.percona.com/downloads/percona-release/redhat/LATEST/
      state: present

  - name: ensure pre-requsites are installed
    yum:
      name:
        - glib2-devel
        - zlib-devel
        - pcre-devel
        - openssl-devel
        - cmake
        - gcc-c++
        - git
      state: present

  - name: remove installed mysql libs
    yum:
      name: mariadb-libs
      state: absent

  - name: install mysql devel
    yum:
      name:
        - Percona-Server-devel-57
        - Percona-Server-server-57
      state: present

  - name: mydumper git repo
    become_user: vagrant
    git:
      accept_hostkey: yes
      repo: https://github.com/maxbube/mydumper.git
      dest: "{{ srcdir }}/"
      update: yes

  - name: clean previous run
    file:
       path: "{{ item }}"
       state: absent
    with_items:
        - "{{ srcdir }}/mydumper"
        - "{{ srcdir }}/myloader"
        - "{{ srcdir }}/CMakeCache.txt"

  - name: cmake mydumper
    command: cmake . -DMYSQL_LIBRARIES_mysqlclient:FILEPATH=/usr/lib64/mysql/libmysqlclient.a
    args:
      chdir: "{{ srcdir }}"

  - name: make mydumper
    make: chdir={{ srcdir }}

  - name: fetch binaries
    fetch:
      src: "{{ item }}"
      dest: "/tmp/src/mydumper/{{ inventory_hostname }}/"
      flat: yes
    with_items:
      - "{{ srcdir }}/mydumper"
      - "{{ srcdir }}/myloader"
