---
- hosts: all
  become: true
  vars:
    srcdir: /tmp/mydumper
  tasks:
  - name: Set a hostname
    ansible.builtin.hostname:
      name: "{{ inventory_hostname }}" 
  - name: debian 9 needs dirmngr
    apt: 
      name: dirmngr
      state: present
    when: ansible_distribution_release == "stretch"
  - name: debian 10 needs gpg 
    apt:
      name: gpg
      state: present
    when: ansible_distribution_release == "buster"
  - name: install percona server apt-key
    apt_key:
      keyserver: "hkp://keys.gnupg.net:80"
      id: 9334A25F8507EFA5
      state: present
      #  - name: Download percona repository pacakge
      #    get_url:
      #      url: "https://repo.percona.com/apt/percona-release_latest{{ ansible_distribution_release }}_all.deb"
      #      dest: /root/percona-release_latest_all.deb
  - name: Install percona repository
    apt:
      deb: "https://repo.percona.com/apt/percona-release_latest.{{ ansible_distribution_release }}_all.deb"
      update_cache: yes
  - name:
    command: percona-release setup ps80

  - name: ensure pre-requsites are installed
    apt:
      name: [ 'cmake','g++','git' ]
      state: present
  - name: ensure pre-requsites to compile are installed
    apt:
      name: [ 'libglib2.0-dev','libperconaserverclient21-dev','zlib1g-dev','libpcre3-dev','libssl-dev' ]
      state: present
  - name: ensure pre-requsites for testing are installed
    command: apt-get -y install percona-server-server libperconaserverclient21
    environment:
      DEBIAN_FRONTEND: noninteractive
      
  - name: Start compiling
    include_tasks: compile_mydumper.yml
    vars:
      srcdir: /tmp/mydumper
      provider: perconaserver
      clientlibpath: /usr/lib/x86_64-linux-gnu/libperconaserverclient.a
      mydumperrepo: https://github.com/maxbube/mydumper.git 
      cmake_options: "{{ extra_cmake_options | default('') }}"      
      branch: master
