---
- hosts: all
  become: true
  vars:
    srcdir: /tmp/mydumper
  tasks:
  - name: debian 9 needs dirmngr
    apt: 
      name: dirmngr
      state: present
    when: ansible_distribution_release == "stretch"
  - name: debian 10 needs gpg 
    apt:
      name: gpg
      state: present
    when: ansible_distribution_release == "buster"
  - name: install percona server apt-key
    apt_key:
      keyserver: "hkp://keys.gnupg.net:80"
      id: 9334A25F8507EFA5
      state: present
  - name: add percona repo
    apt_repository: 
      repo='deb http://repo.percona.com/apt {{ ansible_distribution_release }} main' 
      state=present
  - name: ensure pre-requsites are installed
    apt:
      name: [ 'libglib2.0-dev','zlib1g-dev','libpcre3-dev','libssl-dev','cmake','g++','git','libperconaserverclient20-dev','libperconaserverclient20','percona-server-server-5.7' ]
      state: present
  - name: Start compiling
    include_tasks: compile_mydumper.yml
    vars:
      srcdir: /tmp/mydumper
      provider: perconaserver
      clientlibpath: /usr/lib/x86_64-linux-gnu/libperconaserverclient.a


