---
- hosts: all
  become: true
  tasks:
  - name: Copy test script
    copy:
      src: test
      dest: /root/
  - name: Copy test script
    copy:
      src: test_mydumper.sh
      mode: 0755 
      dest: /root/
  - name: execute
    command: /root/test_mydumper.sh 
