---
- hosts: all
  become: true
  serial: 1
  tasks:
  - name: Copy test script
    copy:
      src: test
      dest: /root/
  - name: Copy test script
    copy:
      src: test_mydumper.sh
      mode: 0755 
      dest: /root/
  - name: "Stop mysql service"
    service:
      name: mysql
      state: stopped
  - name: execute
    command: /root/test_mydumper.sh
 
