---
- hosts: all
  become: true
  tasks:
  - name: Install required package
    apt:
      name: percona-server-test-5.7
      state: present
  - name: Copy the testing environment
    copy:
      src: mydumper
      dest: /usr/lib/mysql-test/suite
  - name: Copy the testing script
    copy:
      src: mydumper_test.sh
      dest: /usr/local/bin/
