---
- hosts: all
  become: true
  vars:
    srcfilename: mydumper_{{ version }}-{{ iteration }}{{ extra_suffix }}.{{ ansible_distribution_release }}_amd64.deb
  tasks:
  - name: Remove previous
    apt:
      name: mydumper
      state: absent
  - name: Copy package
    copy:
      src: "/opt/PKGS/{{ srcfilename }}"
      dest: /tmp/
      #      validate: /usr/sbin/visudo -csf %s
  - name: Install package
    apt:
      deb: "/tmp/{{ srcfilename }}"
  - name: Test mydumper
    command: mydumper
  - name: Test mydumper version
    command: mydumper --version    
    register: cat
  - name: Printing Version
    debug: var=cat.stdout
